---
title: "SocialCognition_Preprocess"
author: "RF"
date: "9/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, 
               janitor, 
               here)
```

## Data preprocessing steps

## Clean up week 46 (follow comments below)
## Add timing files
## Clean up imi-inhibition (follow comments below)


```{r}

CogSci1_timing <- read_csv(here("data","raw","CogSci_2019a_times.csv")) %>%
  mutate(Education = "CogSci",
         Year = 2019,
         Semester = 1,
         Network = 0)

CogSci2_timing <- read_csv(here("data","raw","CogSci_2019b_times.csv")) %>%
  mutate(Education = "CogSci",
         Year = 2019,
         Semester = 1,
         Network = 0)

CogSci_timing <- merge(CogSci1_timing,CogSci2_timing,all=T)
CogSci1_timing <- NULL
CogSci2_timing <- NULL

CogSci1_data <- read_csv(here("data","raw","CogSci_2019a_data.csv")) %>%
  mutate(Education = "CogSci",
         Year = 2019,
         Semester = 1,
         Network = 0)
CogSci2_data <- read_csv(here("data","raw","CogSci_2019b_data.csv")) %>%
  mutate(Education = "CogSci",
         Year = 2019,
         Semester = 1,
         Network = 0)

CogSci_data <- merge(CogSci1_data,CogSci2_data,all=T)
CogSci1_data <- NULL
CogSci2_data <- NULL

CogSci_data <- CogSci_data %>% subset(!is.na(survey.1.player.pid)) %>% remove_empty("cols")

English1_timing <- read_csv(here("data","raw","English_2019a_times.csv")) %>%
  mutate(Education = "English",
         Year = 2019,
         Semester = 1,
         Network = 0)
English2_timing <- read_csv(here("data","raw","English_2019b_times.csv")) %>%
  mutate(Education = "English",
         Year = 2019,
         Semester = 1,
         Network = 0)

English_timing <- merge(English1_timing,English2_timing,all=T)
English1_timing <- NULL
English2_timing <- NULL

English1_data <- read_csv(here("data","raw","English_2019a_data.csv")) %>%
  mutate(Education = "English",
         Year = 2019,
         Semester = 1,
         Network = 0)
English2_data <- read_csv(here("data","raw","English_2019b_data.csv")) %>%
  mutate(Education = "English",
         Year = 2019,
         Semester = 1,
         Network = 0)

English_data <- merge(English1_data,English2_data,all=T)
English1_data <- NULL
English2_data <- NULL

English_data <- English_data %>% subset(!is.na(survey.1.player.pid)) %>% remove_empty("cols")

Linguistics_timing <- read_csv(here("data","raw","Linguistics_2019_times.csv")) %>%
  mutate(Education = "Linguistics",
         Year = 2019,
         Semester = 1,
         Network = 0)
Linguistics_data <- read_csv(here("data","raw","Linguistics_2019_data.csv")) %>%
  mutate(Education = "Linguistics",
         Year = 2019,
         Semester = 1,
         Network = 0)

Linguistics_data <- Linguistics_data %>% subset(!is.na(survey.1.player.pid)) %>% remove_empty("cols")

Nordic1_timing <- read_csv(here("data","raw","Nordic_2019a_times.csv")) %>%
  mutate(Education = "Nordic",
         Year = 2019,
         Semester = 1,
         Network = 0)
Nordic2_timing <- read_csv(here("data","raw","Nordic_2019b_times.csv"))%>%
  mutate(Education = "Nordic",
         Year = 2019,
         Semester = 1,
         Network = 0)

Nordic_timing <- merge(Nordic1_timing,Nordic2_timing,all=T)
Nordic1_timing <- NULL
Nordic2_timing <- NULL

Nordic1_data <- read_csv(here("data","raw","Nordic_2019a_data.csv"))%>%
  mutate(Education = "Nordic",
         Year = 2019,
         Semester = 1,
         Network = 0)
Nordic2_data <- read_csv(here("data","raw","Nordic_2019b_data.csv")) %>%
  mutate(Education = "Nordic",
         Year = 2019,
         Semester = 1,
         Network = 0)

Nordic_data <- merge(Nordic1_data,Nordic2_data,all=T)
Nordic1_data <- NULL
Nordic2_data <- NULL

Nordic_data <- Nordic_data %>% subset(!is.na(survey.1.player.pid)) %>% remove_empty("cols")

Religion_timing <- read_csv(here("data","raw","Religion_2019_times.csv")) %>%
  mutate(Education = "Religion",
         Year = 2019,
         Semester = 1,
         Network = 1)
Religion_data <- read_csv(here("data","raw","Religion_2019_data.csv")) %>%
  mutate(Education = "Religion",
         Year = 2019,
         Semester = 1,
         Network = 1)
Religion_data <- subset(Religion_data, !is.na(participant.label))

W46 <- read_csv(here("data","raw","W46_2019_times.csv"))
W46_data <- read_csv(here("data","raw","W46_2019_data.csv"))
W46_data <- subset(W46_data, !is.na(participant.label))

W47 <- read_csv(here("data","raw","W47_2019_times.csv"))
W47_data <- read_csv(here("data","raw","W47_2019_data.csv"))
W47_data <- subset(W47_data, !is.na(participant.label))

W4647_timing <- merge(W46, W47, all=T) %>% distinct()
W4647_data <- merge(W46_data, W47_data, all=T) %>% distinct()

## Now identify years and studies and semesters
ParticipantList <- read_csv(here("data", "studentlists","participants_list.csv")) %>%
  subset(select = c(code.session1, code.session2, study))

W4647_data <- merge(W4647_data, ParticipantList, 
                    by.x = "participant.code", by.y = "code.session1", all.x = T) %>%
  rename(Education = study) %>%
  mutate(Year = 2019,
         Semester = 1,
         Network = 1)

CogSci_2020_data <- read_csv(here("data","raw","CogSci_2020_data.csv")) %>%
  mutate(Education = "CogSci",
         Year = 2020,
         Semester = 1,
         Network = 0)
CogSci_2020_data <- subset(CogSci_2020_data, !is.na(participant.label))


CogSci_data$participant.label <- NA
CogSci_data$break.1.player.id_in_group <- NA
CogSci_data$break.1.player.payoff <- NA
CogSci_data$break.1.group.id_in_subsession <- NA
CogSci_data$break.1.subsession.round_number <- NA

data <- rbind(
  CogSci_data,
  English_data,
  Linguistics_data,
  Nordic_data
)

## Now add the missing columns to merge with Religion
MissingOnes <- colnames(Religion_data)[!(colnames(Religion_data) %in% colnames(data))]
data[,MissingOnes] = NA

data <- rbind(
  data,
  Religion_data
)

# Now add week 46-47
MissingOnes <- colnames(W4647_data)[!(colnames(W4647_data) %in% colnames(data))]
data[,MissingOnes] = NA
MissingOnes <- colnames(data)[!(colnames(data) %in% colnames(W4647_data))]
W4647_data[,MissingOnes] = NA

x<- compare_df_cols(data,
  W4647_data)
x[x$data != x$W4647_data,]

cols.char <- c("network_followup.1.player.friend1",
         "network_followup.1.player.friend2",
         "network_followup.1.player.friend3",
         "network_followup.1.player.friend4",
         "network_followup.1.player.friend5",
         "network_followup.1.player.friend6",
         "network_followup.1.player.friend7",
         "network_followup.1.player.friend8",
         "survey_network.1.player.computer",
         "survey_network.1.player.gender",
         "survey_network.1.player.introweek",
         "survey_network.1.player.language",
         "survey_network.1.player.pid",
         "code.session2",
         "survey_network.1.player.study")

cols.num <- c("survey_network.1.player.age",
         "network_followup.1.player.scale1",
         "network_followup.1.player.scale2",
         "network_followup.1.player.scale3",
         "network_followup.1.player.scale4",
         "network_followup.1.player.scale5",
         "network_followup.1.player.scale6",
         "network_followup.1.player.scale7",
         "network_followup.1.player.scale8")
         
data[cols.char] <- sapply(data[cols.char],as.character)
data[cols.num] <- sapply(data[cols.num],as.numeric)

cols.num <- c("survey_followup.1.group.id_in_subsession",
              "survey_followup.1.player.age",
              "survey_followup.1.player.id_in_group",
              "survey_followup.1.player.payoff",
              "survey_followup.1.subsession.round_number")

cols.char <- c("survey_followup.1.player.computer",
               "survey_followup.1.player.gender",
               "survey_followup.1.player.introweek",
               "survey_followup.1.player.language",
               "survey_followup.1.player.pid")

W4647_data[cols.char] <- sapply(W4647_data[cols.char],as.character)
W4647_data[cols.num] <- sapply(W4647_data[cols.num],as.numeric)

colnames(W4647_data)[!(colnames(W4647_data) %in% colnames(data))]

data <- rbind(
  data,
  W4647_data
)

## Clean up false participants
unique(data$survey.1.player.pid)
data <- subset(data, !(grepl("fake",survey.1.player.pid )))
unique(data$survey.1.player.pid)

d <- subset(data,is.na(survey.1.player.pid))
pl <- read_csv(here("data", "studentlists","participants_list.csv")) %>%
  subset(code.session1 %in% d$participant.code)
data$survey.1.player.pid[is.na(data$survey.1.player.pid)] <- pl$pid

## Follow up. Last call contains: survey, network, ToM
## N.B. The network replaces those for CogSci Ling Nordic and English, the other educations were far enough that they already have networks.
LastCall_CogSciLing <- read_csv(here("data","raw", "LastCall_CogSciLing_2019_times.csv"))
LastCall_CogSciLing_data <- read_csv(here("data","raw", "LastCall_CogSciLing_2019_data.csv"))

LastCall_NordiskEng <- read_csv(here("data","raw", "LastCall_NordiskEng_2019_times.csv"))
LastCall_NordiskEng_data <- read_csv(here("data","raw", "LastCall_NordiskEng_2019_data.csv"))

LastCall_timing <- merge(LastCall_CogSciLing, LastCall_NordiskEng, all = T)
LastCall_data <- merge(LastCall_CogSciLing_data, LastCall_NordiskEng_data, all = T)

LastCall_CogSciLing <- NULL
LastCall_CogSciLing_data  <- NULL
LastCall_NordiskEng <- NULL
LastCall_NordiskEng_data <- NULL

LastCall_data <- merge(LastCall_data, ParticipantList, 
                    by.x = "participant.code", by.y = "code.session2", all.x = T) %>%
  rename(Education = study) %>%
  mutate(Year = 2019,
         Semester = 1,
         Network = 1)
LastCall_data$Education[LastCall_data$Education=="Nordisk"]<-"Nordic"

l <- subset(LastCall_data, is.na(Education))

LastCall_data$Education[is.na(LastCall_data$Education) & LastCall_data$survey_followup.1.player.study %in% c("Nordisk", "Nordisk sprog og litteratur")] <- "Nordic"
LastCall_data$Education[is.na(LastCall_data$Education) & LastCall_data$survey_followup.1.player.study %in% c("english", "English")] <- "English"

## Nb. 382 raws are indicated as study = test
LastCall_data <- LastCall_data %>% subset(survey_followup.1.player.study != "test")

l <- subset(LastCall_data, is.na(Education))
```

## Network data
N.B. use the anonymous hash as label

```{r}
pacman::p_load(tidyverse, 
               ggraph, 
               tidytext, 
               readxl, 
               igraph, 
               tidygraph, 
               stringr, 
               stringi)

## Cogsci 2019

CogSci_Intro <- CogSci_data %>%
  select(
    survey.1.player.pid,
    network.1.player.id_in_group:network.1.subsession.round_number           
  ) %>% mutate(
    survey.1.player.pid = gsub("sarah hvid andersen","Sarah Hvid Andersen",survey.1.player.pid),
    survey.1.player.pid = gsub("Gustav Alfred vous metzsch", "Gustav Meltzch",survey.1.player.pid)
  )

CogSci_Followup <- LastCall_data %>%
  subset(grepl("CogSci", Education)) %>%
  select(
    survey_followup.1.player.pid,
    network_cogsci.1.player.friend1:network_cogsci.1.subsession.round_number           
  ) %>% mutate(
    network_cogsci.1.player.friend1 = gsub("laerke braedder","lærke b",network_cogsci.1.player.friend1))

colnames(CogSci_Followup) <- gsub("_cogsci.","_followup.",colnames(CogSci_Followup))

key <- read_delim(here("data", "keys", "CogSci_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

NewNames <- data.frame(key = sort(unique(tolower(c(
    CogSci_Followup$network_followup.1.player.studymate1,
    CogSci_Followup$network_followup.1.player.studymate2,
    CogSci_Followup$network_followup.1.player.studymate3,
    CogSci_Followup$network_followup.1.player.studymate4,
    CogSci_Followup$network_followup.1.player.studymate5,
    CogSci_Followup$network_followup.1.player.student1,
    CogSci_Followup$network_followup.1.player.student2,
    CogSci_Followup$network_followup.1.player.student3,
    CogSci_Followup$network_followup.1.player.student4,
    CogSci_Followup$network_followup.1.player.student5,
    CogSci_Followup$network_followup.1.player.student6,
    CogSci_Followup$network_followup.1.player.student7,
    CogSci_Followup$network_followup.1.player.student8,
    CogSci_Followup$network_followup.1.player.student9,
    CogSci_Followup$network_followup.1.player.student10,
    CogSci_Followup$network_followup.1.player.student11,
    CogSci_Followup$network_followup.1.player.student12,
    CogSci_Followup$network_followup.1.player.student13,
    CogSci_Followup$network_followup.1.player.student14,
    CogSci_Followup$network_followup.1.player.student15,
    CogSci_Followup$network_followup.1.player.student16,
    CogSci_Followup$network_followup.1.player.student17,
    CogSci_Followup$network_followup.1.player.student18,
    CogSci_Followup$network_followup.1.player.student19,
    CogSci_Followup$network_followup.1.player.student20,
    CogSci_Followup$network_followup.1.player.student21,
    CogSci_Followup$network_followup.1.player.student22,
    CogSci_Followup$network_followup.1.player.student23,
    CogSci_Followup$network_followup.1.player.student24,
    CogSci_Followup$network_followup.1.player.student25,
    CogSci_Followup$network_followup.1.player.student26,
    CogSci_Followup$network_followup.1.player.student27,
    CogSci_Followup$network_followup.1.player.student28,
    CogSci_Followup$network_followup.1.player.student29,
    CogSci_Followup$network_followup.1.player.student30,
    CogSci_Followup$network_followup.1.player.student31,
    CogSci_Followup$network_followup.1.player.student32,
    CogSci_Followup$network_followup.1.player.student33,
    CogSci_Followup$network_followup.1.player.student34,
    CogSci_Followup$network_followup.1.player.student35,
    CogSci_Followup$network_followup.1.player.student36,
    CogSci_Followup$network_followup.1.player.student37,
    CogSci_Followup$network_followup.1.player.student38,
    CogSci_Followup$network_followup.1.player.student39,
    CogSci_Followup$network_followup.1.player.student40,
    CogSci_Followup$network_followup.1.player.student41,
    CogSci_Followup$network_followup.1.player.student42,
    CogSci_Followup$network_followup.1.player.student43,
    CogSci_Followup$network_followup.1.player.student44,
    CogSci_Followup$network_followup.1.player.student45,
    CogSci_Followup$network_followup.1.player.student46,
    CogSci_Followup$network_followup.1.player.student47,
    CogSci_Followup$network_followup.1.player.student48,
    CogSci_Followup$network_followup.1.player.student49,
    CogSci_Followup$network_followup.1.player.student50,
    CogSci_Followup$network_followup.1.player.student51,
    CogSci_Followup$network_followup.1.player.student52,
    CogSci_Followup$network_followup.1.player.student53,
    CogSci_Followup$network_followup.1.player.student54,
    CogSci_Followup$network_followup.1.player.student55,
    CogSci_Followup$network_followup.1.player.student56,
    CogSci_Followup$network_followup.1.player.student57,
    CogSci_Followup$network_followup.1.player.student58,
    CogSci_Followup$network_followup.1.player.student59,
    CogSci_Followup$network_followup.1.player.student60,
    CogSci_Followup$network_followup.1.player.student61,
    CogSci_Followup$network_followup.1.player.student62)))))

NewNames$key[!(NewNames$key %in% key$key)]

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(CogSci_Intro, key, uniqueKey)
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2019_n0.csv"))

edges <- CreateEdges_cogsci19n1(CogSci_Followup, key, uniqueKey)
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2019_n1.csv"))

### Study Group, Fun and Study edges
edges <- CreateEdges_cogsci19_label(CogSci_Followup, key, uniqueKey, "StudyGroup")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2019_n1_studyGroup.csv"))
edges <- CreateEdges_cogsci19_label(CogSci_Followup, key, uniqueKey, "Fun")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2019_n1_Fun.csv"))
edges <- CreateEdges_cogsci19_label(CogSci_Followup, key, uniqueKey, "Studious")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2019_n1_Studious.csv"))

nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_CogSci_2019.csv"))

### DESIGN
Design_Followup <- data %>%
  subset(Education == "Design") %>%
  select(
    survey.1.player.pid,
    network.1.player.friend1:network.1.subsession.round_number           
  )

Names <- data.frame(key = sort(unique(tolower(c(
    Design_Followup$survey.1.player.pid,
    Design_Followup$network.1.player.friend1,
    Design_Followup$network.1.player.friend2,
    Design_Followup$network.1.player.friend3,
    Design_Followup$network.1.player.friend4,
    Design_Followup$network.1.player.friend5,
    Design_Followup$network.1.player.friend6,
    Design_Followup$network.1.player.friend7,
    Design_Followup$network.1.player.friend8,
    Design_Followup$network.1.player.friend9,
    Design_Followup$network.1.player.friend10
    )))))

write_delim(Names, here("data", "keys", "temp", "Design_2019_key.csv"),delim=",")
key <- read_delim(here("data", "keys", "Design_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(Design_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Design_2019_n1.csv"))
nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_Design_2019_n1.csv"))

## English

English_Intro <- English_data %>%
  select(
    survey.1.player.pid,
    network.1.player.id_in_group:network.1.subsession.round_number           
  )

English_Followup <- LastCall_data %>%
  subset(Education == "English") %>%
  select(
    survey_followup.1.player.pid,
    network_followup.1.player.friend1:network_followup.1.subsession.round_number           
  )

Names <- CreateKey(English_Intro, English_Followup)
write_delim(Names, here("data", "keys", "temp","English_2019_key.csv"),delim=",")

key <- read_delim(here("data", "keys", "English_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

NewNames <- data.frame(key = sort(unique(tolower(c(
    English_Followup$network_followup.1.player.studymate1,
    English_Followup$network_followup.1.player.studymate2,
    English_Followup$network_followup.1.player.studymate3,
    English_Followup$network_followup.1.player.studymate4,
    English_Followup$network_followup.1.player.studymate5)))))

NewNames$key[!(NewNames$key %in% key$key)]

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(English_Intro, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_English_2019_n0.csv"))

edges <- CreateEdges_followup(English_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_English_2019_n1.csv"))

edges <- CreateEdges_label(English_Followup, key, uniqueKey, "StudyGroup")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_English_2019_n1_studyGroup.csv"))

edges <- CreateEdges_label(English_Followup, key, uniqueKey, "Fun")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_English_2019_n1_Fun.csv"))

edges <- CreateEdges_label(English_Followup, key, uniqueKey, "Studious")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_English_2019_n1_Studious.csv"))

nodes <- data.frame(ID = unique(key$label))
write_csv(edges, here("data", "networks", "nodes_English_2019.csv"))

### Informationsvidenskab
Information_Followup <- data %>%
  subset(Education == "Information") %>%
  select(
    survey.1.player.pid,
    network.1.player.friend1:network.1.subsession.round_number           
  )

Names <- data.frame(key = sort(unique(tolower(c(
    Information_Followup$survey.1.player.pid,
    Information_Followup$network.1.player.friend1,
    Information_Followup$network.1.player.friend2,
    Information_Followup$network.1.player.friend3,
    Information_Followup$network.1.player.friend4,
    Information_Followup$network.1.player.friend5,
    Information_Followup$network.1.player.friend6,
    Information_Followup$network.1.player.friend7,
    Information_Followup$network.1.player.friend8,
    Information_Followup$network.1.player.friend9,
    Information_Followup$network.1.player.friend10)))))

write_delim(Names, here("data", "keys", "temp", "Information_2019_key.csv"),delim=",")
key <- read_delim(here("data", "keys", "Information_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(Information_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Information_2019_n1.csv"))
nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_Information_2019_n1.csv"))

# Linguistics
Linguistics_Intro <- Linguistics_data %>%
  select(
    survey.1.player.pid,
    network.1.player.id_in_group:network.1.subsession.round_number           
  )

Linguistics_Followup <- LastCall_data %>%
  subset(Education=="Linguistics") %>%
  select(
    survey_followup.1.player.pid,
    network_followup.1.player.friend1:network_followup.1.subsession.round_number           
  ) 

Names <- CreateKey(Linguistics_Intro, Linguistics_Followup)

write_delim(Names, here("data", "keys", "temp", "Linguistics_2019_key.csv"),delim=",")
key <- read_delim(here("data", "keys", "Linguistics_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

NewNames <- data.frame(key = sort(unique(tolower(c(
    Linguistics_Followup$network_followup.1.player.studymate1,
    Linguistics_Followup$network_followup.1.player.studymate2,
    Linguistics_Followup$network_followup.1.player.studymate3,
    Linguistics_Followup$network_followup.1.player.studymate4,
    Linguistics_Followup$network_followup.1.player.studymate5)))))

NewNames$key[!(NewNames$key %in% key$key)]
  
uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(Linguistics_Intro, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Linguistics_2019_n0.csv"))

edges <- CreateEdges_followup(Linguistics_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Linguistics_2019_n1.csv"))

edges <- CreateEdges_label(Linguistics_Followup, key, uniqueKey, "StudyGroup")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_Linguistics_2019_n1_studyGroup.csv"))

edges <- CreateEdges_label(Linguistics_Followup, key, uniqueKey, "Fun")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_Linguistics_2019_n1_Fun.csv"))

edges <- CreateEdges_label(Linguistics_Followup, key, uniqueKey, "Studious")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_Linguistics_2019_n1_Studious.csv"))

nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_Linguistics_2019.csv"))

### Media
Media_Followup <- data %>%
  subset(Education == "Media") %>%
  select(
    survey.1.player.pid,
    network.1.player.friend1:network.1.subsession.round_number           
  )

Names <- data.frame(key = sort(unique(tolower(c(
    Media_Followup$survey.1.player.pid,
    Media_Followup$network.1.player.friend1,
    Media_Followup$network.1.player.friend2,
    Media_Followup$network.1.player.friend3,
    Media_Followup$network.1.player.friend4,
    Media_Followup$network.1.player.friend5,
    Media_Followup$network.1.player.friend6,
    Media_Followup$network.1.player.friend7,
    Media_Followup$network.1.player.friend8,
    Media_Followup$network.1.player.friend9,
    Media_Followup$network.1.player.friend10)))))

write_delim(Names, here("data", "keys", "temp", "Media_2019_key.csv"),delim=",")
key <- read_delim(here("data", "keys", "Media_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(Media_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Media_2019_n1.csv"))
nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_Media_2019.csv"))

# Nordic
Nordic_Intro <- Nordic_data %>%
  select(
    survey.1.player.pid,
    network.1.player.id_in_group:network.1.subsession.round_number           
  )

Nordic_Followup <- LastCall_data %>%
  subset(Education == "Nordic") %>%
  select(
    survey_followup.1.player.pid,
    network_followup.1.player.friend1:network_followup.1.subsession.round_number           
  ) 

Names <- CreateKey(Nordic_Intro, Nordic_Followup)
write_csv(Names, here("data", "keys", "temp", "Nordic_2019_key.csv"))

key <- read_delim(here("data", "keys", "Nordic_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))
NewNames <- data.frame(key = sort(unique(tolower(c(
    Nordic_Followup$network_followup.1.player.studymate1,
    Nordic_Followup$network_followup.1.player.studymate2,
    Nordic_Followup$network_followup.1.player.studymate3,
    Nordic_Followup$network_followup.1.player.studymate4,
    Nordic_Followup$network_followup.1.player.studymate5)))))

NewNames$key[!(NewNames$key %in% key$key)]

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(Nordic_Intro, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Nordic_2019_n0.csv"))

edges <- CreateEdges_followup(Nordic_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Nordic_2019_n1.csv"))

edges <- CreateEdges_label(Nordic_Followup, key, uniqueKey, "StudyGroup")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_Nordic_2019_n1_studyGroup.csv"))

edges <- CreateEdges_label(Nordic_Followup, key, uniqueKey, "Fun")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_Nordic_2019_n1_Fun.csv"))

edges <- CreateEdges_label(Nordic_Followup, key, uniqueKey, "Studious")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_Nordic_2019_n1_Studious.csv"))

nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_Nordic_2019.csv"))

# Religion

Religion_Followup <- data %>%
  subset(Education == "Religion") %>%
  select(
    survey.1.player.pid,
    network.1.player.friend1:network.1.subsession.round_number           
  )

Names <- data.frame(key = sort(unique(tolower(c(
    Religion_Followup$survey.1.player.pid,
    Religion_Followup$network.1.player.friend1,
    Religion_Followup$network.1.player.friend2,
    Religion_Followup$network.1.player.friend3,
    Religion_Followup$network.1.player.friend4,
    Religion_Followup$network.1.player.friend5,
    Religion_Followup$network.1.player.friend6,
    Religion_Followup$network.1.player.friend7,
    Religion_Followup$network.1.player.friend8,
    Religion_Followup$network.1.player.friend9,
    Religion_Followup$network.1.player.friend10)))))

write_delim(Names, here("data", "keys", "temp", "Religion_2019_key.csv"),delim=",")
key <- read_delim(here("data", "keys", "Religion_2019_key.csv"),delim=",") %>%
  mutate(key = tolower(key))

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

edges <- CreateEdges_intro(Religion_Followup, key, uniqueKey)
sort(unique(c(edges$from,edges$to)))
write_csv(edges, here("data", "networks", "edges_Religion_2019_n1.csv"))
nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_Religion_2019.csv"))

## CogSci 2020
CogSci_2020_n0 <- CogSci_2020_data %>%
  select(
    survey.1.player.pid,
    network_followup.1.player.id_in_group:network_followup.1.subsession.round_number  
  )
Names <- data.frame(key = sort(unique(tolower(c(
    CogSci_2020_n0$survey.1.player.pid,
    CogSci_2020_n0$network_followup.1.player.friend1,
    CogSci_2020_n0$network_followup.1.player.friend2,
    CogSci_2020_n0$network_followup.1.player.friend3,
    CogSci_2020_n0$network_followup.1.player.friend4,
    CogSci_2020_n0$network_followup.1.player.friend5,
    CogSci_2020_n0$network_followup.1.player.friend6,
    CogSci_2020_n0$network_followup.1.player.friend7,
    CogSci_2020_n0$network_followup.1.player.friend8,
    CogSci_2020_n0$network_followup.1.player.friend9,
    CogSci_2020_n0$network_followup.1.player.friend10)))))
write_csv(Names, here("data", "keys", "temp", "CogSci_2020_n0_key.csv"))

key <- read_delim(here("data", "keys", "CogSci_2020_n0_key.csv"),delim=",") %>%
  mutate(key = tolower(key)) %>% distinct()

NewNames <- data.frame(key = sort(unique(tolower(c(
    CogSci_2020_n0$network_followup.1.player.studymate1,
    CogSci_2020_n0$network_followup.1.player.studymate2,
    CogSci_2020_n0$network_followup.1.player.studymate3,
    CogSci_2020_n0$network_followup.1.player.studymate4,
    CogSci_2020_n0$network_followup.1.player.studymate5)))))

NewNames$key[!(NewNames$key %in% key$key)]

uniqueKey <- data.frame(
  label = as.character(unique(key$label)),
  IDx = sample(seq(length(unique(key$label)))))

CogSci_2020_n0 <- CogSci_2020_n0 %>%
  rename(survey_followup.1.player.pid=survey.1.player.pid)
edges <- CreateEdges_followup(CogSci_2020_n0, key, uniqueKey)
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2020_n0.csv"))

edges <- CreateEdges_label(CogSci_2020_n0, key, uniqueKey, "StudyGroup")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2020_n0_studyGroup.csv"))

edges <- CreateEdges_label(CogSci_2020_n0, key, uniqueKey, "Fun")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2020_n0_Fun.csv"))

edges <- CreateEdges_label(CogSci_2020_n0, key, uniqueKey, "Studious")
unique(c(edges$from,edges$to))
write_csv(edges, here("data", "networks", "edges_CogSci_2020_n0_Studious.csv"))

nodes <- data.frame(ID = unique(key$label))
write_csv(nodes, here("data", "networks", "nodes_CogSci_2020_n0.csv"))

```

## Gumballs

```{r}
## data
## CogSci2020
## CogSci2018

dd <- data %>%
  select(
    colnames(data)[grepl("participant|gambler|Education|Year",colnames(data))]
  )

dd_cs20 <- CogSci_2020_data %>%
  select(
    colnames(CogSci_2020_data)[grepl("participant|gambler|Education|Year",colnames(CogSci_2020_data))]
  )

MissingOnes <- colnames(dd_cs20)[!(colnames(dd_cs20) %in% colnames(dd))]
dd[,MissingOnes] = NA

xx<-janitor::compare_df_cols(dd,dd_cs20)
xxx<-xx[is.na(xx$dd!=xx$dd_cs20),]
#colnames(dd)
dd <- rbind(dd,dd_cs20)

## What to do w strategy?

d_opponent <- dd %>% 
  gather(trial, opponent, colnames(dd)[grepl("opponent",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  opponent
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_nBlueOn8 <- dd %>% 
  gather(trial, nBlueOn8, colnames(dd)[grepl("nBlueOn8",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  nBlueOn8
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_firstChoice <- dd %>% 
  gather(trial, firstChoice, colnames(dd)[grepl("firstChoice",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  firstChoice
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_botChoice <- dd %>% 
  gather(trial, botChoice, colnames(dd)[grepl("botChoice",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  botChoice
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_secondChoice <- dd %>% 
  gather(trial, secondChoice, colnames(dd)[grepl("secondChoice",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  secondChoice
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_finalDraw <- dd %>% 
  gather(trial, finalDraw, colnames(dd)[grepl("finalDraw",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  finalDraw
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_right <- dd %>% 
  gather(trial, right, colnames(dd)[grepl("right",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  right
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
      
d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("payoff",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_strategy <- dd %>% 
  gather(trial, strategy, colnames(dd)[grepl("strategy",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  strategy
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_groupID <- dd %>% 
  gather(trial, groupID, colnames(dd)[grepl("subsession",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  groupID
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_opponent,
  d_nBlueOn8
)


ddd <- merge(
  ddd,
  d_firstChoice)

ddd <- merge(
  ddd,
  d_botChoice)

ddd <- merge(
  ddd,
  d_secondChoice)

ddd <- merge(
  ddd,
  d_finalDraw)

ddd <- merge(
  ddd,
  d_right)

ddd <- merge(
  ddd,
  d_payoff)

ddd <- merge(
  ddd,
  d_strategy)

#ddd <- merge(
#  ddd,
#  d_groupID)

ddd_cs18 <- read_csv("data/raw/CogSci18/GumballsData_CogSci18.csv") %>%
  rename(
    firstChoice = FirstChoice,
    secondChoice = SecondChoice,
    trial = Trial,
    participant.id_in_session = ID,
    nBlueOn8 = SampledBlues,
    right = Rational,
    botChoice = OtherChoice
  ) %>% mutate(
    Year = 2018,
    Education = "CogSci",
    strategy = NA,
    opponent = "Other Player",
    finalDraw = NA,
    payoff = NA
  )

janitor::compare_df_cols(ddd, ddd_cs18)
GumballsData <- rbind(ddd, ddd_cs18)
GumballsData$payoff <- NULL

x <- GumballsData[is.na(GumballsData$firstChoice),]
## Participants with missing data "v2k67w8n" "gi3xxttp"
x <- GumballsData[is.na(GumballsData$right ),]
## Participants with missing data "v2k67w8n"

GumballsData <- subset(GumballsData, !is.na(firstChoice))
write_csv(GumballsData,here("data", "clean", "Gumballs_data.csv"))

```


# TRUST
```{r}
## N.B: not used in CogSci 2020
dd <- data %>%
  select(
    colnames(data)[grepl("participant|trust|Education|Year",colnames(data))]
  ) %>% rename(
    participantPayoff = participant.payoff,
    totalPayoff = total.1.player.payoff_trust,
    totalPayoff_Fee = participant.payoff_plus_participation_fee
  )

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  id_in_group,
  totalPayoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("payoff",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_id_in_subsession <- dd %>% 
  gather(trial, id_in_subsession, colnames(dd)[grepl("id_in_subsession",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  id_in_subsession
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_sent_amount <- dd %>% 
  gather(trial, sent_amount, colnames(dd)[grepl("sent_amount",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  sent_amount
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_sent_back_amount <- dd %>% 
  gather(trial, sent_back_amount, colnames(dd)[grepl("sent_back_amount",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  sent_back_amount
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_id_in_group,
  d_payoff
)

ddd <- merge(
  ddd,
  d_id_in_subsession)

ddd <- merge(
  ddd,
  d_sent_amount)

ddd <- merge(
  ddd,
  d_sent_back_amount)

x <- ddd %>% group_by(participant.code) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())

TrustData <- ddd
x <- subset(TrustData, is.na(sent_back_amount))
unique(x$participant.code)
#Missing data in "gudd7h7a" "v2k67w8n" "b6o4nz16" "jrkge8hp"
TrustData <- subset(TrustData, !is.na(TrustData$sent_amount))
write_csv(TrustData, here("data", "clean", "Trust_data.csv"))
```

# PRISONER
```{r}
dd <- data %>%
  select(
    colnames(data)[grepl("participant|Education|Year|prisoner\\.",colnames(data))]
  )
dd_cs20 <- CogSci_2020_data %>%
  select(
    colnames(CogSci_2020_data)[grepl("participant|prisoner\\.|Education|Year",colnames(CogSci_2020_data))]
  )

xx<-janitor::compare_df_cols(dd,dd_cs20)

MissingOnes <- colnames(dd_cs20)[!(colnames(dd_cs20) %in% colnames(dd))]
dd[,MissingOnes] = NA

xx<-janitor::compare_df_cols(dd,dd_cs20)
xxx<-xx[is.na(xx$dd!=xx$dd_cs20),]
#colnames(dd)
dd <- rbind(dd,dd_cs20) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  id_in_group,
  participantPayoff,
  participantPayoff_Fee
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_decision <- dd %>% 
  gather(trial, decision, colnames(dd)[grepl("decision",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  decision
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("payoff",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_id_in_subsession <- dd %>% 
  gather(trial, id_in_subsession, colnames(dd)[grepl("id_in_subsession",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  id_in_subsession
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_id_in_group,
  d_decision
)
ddd <- merge(
  ddd,
  d_payoff)

ddd <- merge(
  ddd,
  d_id_in_subsession)

x <- ddd %>% group_by(participant.code) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())

PrisonerData <- ddd
x <- PrisonerData %>% subset(is.na(id_in_group))
unique(x$participant.code)
## Missing data: "gudd7h7a" "v2k67w8n" "b6o4nz16" "jrkge8hp"
PrisonerData <- PrisonerData %>% subset(!is.na(id_in_group))
write_csv(PrisonerData, here("data", "clean", "Prisoner_data.csv"))
```

# PRISONER RETALIATION
```{r}

dd <- data %>%
  select(
    colnames(data)[grepl("participant|Education|Year|prisoner_retaliation",colnames(data))]
  )

dd_cs20 <- CogSci_2020_data %>%
  select(
    colnames(CogSci_2020_data)[grepl("participant|prisoner_retaliation|Education|Year",colnames(CogSci_2020_data))]
  )

xx<-janitor::compare_df_cols(dd,dd_cs20)

dd <- rbind(dd,dd_cs20) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  id_in_group,
  participantPayoff,
  participantPayoff_Fee
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_decision <- dd %>% 
  gather(trial, decision, colnames(dd)[grepl("decision",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  decision
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_id_in_subsession <- dd %>% 
  gather(trial, id_in_subsession, colnames(dd)[grepl("id_in_subsession",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  id_in_subsession
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("payoff",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_botChoice <- dd %>% 
  gather(trial, botChoice, colnames(dd)[grepl("botchoice",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  botChoice
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_id_in_group,
  d_payoff
)

ddd <- merge(
  ddd,
  d_id_in_subsession)

ddd <- merge(
  ddd,
  d_decision)

ddd <- merge(
  ddd,
  d_botChoice)

x <- ddd %>% group_by(participant.code) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())

PrisonerRetaliationData <- ddd
summary(PrisonerRetaliationData)
x <- PrisonerRetaliationData %>% subset(is.na(id_in_group))
unique(x$participant.code)
#Missing data "gudd7h7a" "v2k67w8n" "b6o4nz16" "jrkge8hp"
PrisonerRetaliationData <- PrisonerRetaliationData %>% subset(!is.na(id_in_group))
write_csv(PrisonerRetaliationData, here("data", "clean", "PrisonerRetaliation_data.csv"))

```

# CRD SEQUENTIAL
```{r}
# N.B. no cogsci 2020

dd <- data %>%
  select(
    colnames(data)[grepl("participant|Education|Year|CRD_sequential",colnames(data))]
  ) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )
dd <- dd %>% rename(Round = CRD_sequential.1.group.contribution_round)
colnames(dd) <- gsub("sequential.1","sequential",colnames(dd))
colnames(dd) <- gsub("\\.contribution",".contribution0",colnames(dd))
colnames(dd)

d_contribution <- dd %>% 
  gather(trial, contribution, colnames(dd)[grepl("\\.contribution",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.id_in_group = CRD_sequential.player.id_in_group,
  participant.id_in_subsession = CRD_sequential.group.id_in_subsession,
  participant.code,
  Education,
  Year,
  trial,
  Round,
  contribution,
  moneyLeft = CRD_sequential.player.moneyLeft,
  spent = CRD_sequential.player.spent,
  sumContribution = CRD_sequential.player.sumContribution,
  payoff = CRD_sequential.player.payoff,
  totalContribution = CRD_sequential.group.total_contribution,
  lost = CRD_sequential.group.lost
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_pot <- dd %>% 
  gather(trial, pot, colnames(dd)[grepl("\\.pot",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  pot
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_contribution,
  d_pot
)

x <- ddd %>% group_by(participant.code) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())

CRD_Data <- ddd
summary(CRD_Data)
x <- CRD_Data %>% subset(is.na(pot))
unique(x$participant.code)
#MissingData "b6o4nz16" "gudd7h7a" "jrkge8hp" "v2k67w8n"
CRD_Data <- CRD_Data %>% subset(!is.na(pot))
write_csv(CRD_Data, here("data", "clean", "CRD_data.csv"))

```

# MATCHING PENNIES
```{r}
# data has matching pennies
# Lastcall

dd <- data %>%
  select(
    colnames(data)[grepl("participant|Education|Year|matching_pennies",colnames(data))]
  ) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )
colnames(dd)

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  id_in_group
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_penny_side <- dd %>% 
  gather(trial, penny_side, colnames(dd)[grepl("penny_side",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  penny_side
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_is_winner <- dd %>% 
  gather(trial, is_winner, colnames(dd)[grepl("is_winner",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  is_winner
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
 
d_bot_side <- dd %>% 
  gather(trial, bot_side, colnames(dd)[grepl("bot_side",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  bot_side
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
 
d_bot_strategy <- dd %>% 
  gather(trial, bot_strategy, colnames(dd)[grepl("bot_strategy",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  bot_strategy
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
    
d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("payoff",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
ddd <- merge(
  d_id_in_group,
  d_penny_side
)

ddd <- merge(
  ddd,
  d_is_winner
)
ddd <- merge(
  ddd,
  d_bot_side
)
ddd <- merge(
  ddd,
  d_bot_strategy
)
ddd <- merge(
  ddd,
  d_payoff
)
x <- ddd %>% group_by(participant.code) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())

MatchingPennies_Data <- ddd
summary(MatchingPennies_Data)
MatchingPennies_Data <- MatchingPennies_Data %>% subset(!is.na(id_in_group) & !is.na(penny_side))
x <- MatchingPennies_Data %>% subset(is.na(is_winner))
write_csv(MatchingPennies_Data, here("data", "clean", "MatchingPennies_data.csv"))

### Last Call & CogSci 2020 human opponent

dd_lc <- LastCall_data %>%
  select(
    colnames(LastCall_data)[grepl("participant|Education|Year|ToM_penny",colnames(LastCall_data))]
  )
### CogSci 2020
dd_cs <- CogSci_2020_data %>%
  select(
    colnames(CogSci_2020_data)[grepl("participant|Education|Year|ToM_penny",colnames(CogSci_2020_data))]
  )

x<-janitor::compare_df_cols(dd_lc,dd_cs)
MissingOnes <- colnames(dd_lc)[!(colnames(dd_lc) %in% colnames(dd_cs))]
dd_cs[,MissingOnes] = NA

xx<-janitor::compare_df_cols(dd,dd_cs)
xxx<-xx[is.na(xx$dd!=xx$dd_cs),]
#colnames(dd)
dd <- rbind(dd_lc,dd_cs) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  id_in_group
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_level <- dd %>% 
  gather(trial, tom_level, colnames(dd)[grepl("tom_level",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_level
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_player_role <- dd %>% 
  gather(trial, player_role, colnames(dd)[grepl("player_role",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  player_role
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_role <- dd %>% 
  gather(trial, tom_role, colnames(dd)[grepl("tom_role",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_role
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_decision <- dd %>% 
  gather(trial, decision, colnames(dd)[grepl("player.decision",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  decision
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_decision <- dd %>% 
  gather(trial, tom_decision, colnames(dd)[grepl("tom_decision",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_decision
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_player_payoff <- dd %>% 
  gather(trial, player_payoff, colnames(dd)[grepl("player_payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  player_payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_payoff <- dd %>% 
  gather(trial, tom_payoff, colnames(dd)[grepl("tom_payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_state <- dd %>% 
  gather(trial, tom_state, colnames(dd)[grepl("tom_state",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_state
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("player\\.payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_id_in_group,
  d_tom_level
) 
ddd <- merge(
  ddd,
  d_player_role
) 
ddd <- merge(
  ddd,
  d_tom_role
) 
ddd <- merge(
  ddd,
  d_decision
)
ddd <- merge(
  ddd,
  d_tom_decision
)
ddd <- merge(
  ddd,
  d_player_payoff
)
ddd <- merge(
  ddd,
  d_tom_payoff
)
ddd <- merge(
  ddd,
  d_tom_state
)
ddd <- merge(
  ddd,
  d_payoff
)
MatchingPennies2_Data <- subset(ddd, !is.na(id_in_group))
summary(MatchingPennies2_Data)

### CogSci 2020 - algorithm opponent
dd <- CogSci_2020_data %>%
  select(
    colnames(CogSci_2020_data)[grepl("participant|Education|Year|ToM_Slot",colnames(CogSci_2020_data))]
  ) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  id_in_group
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_level <- dd %>% 
  gather(trial, tom_level, colnames(dd)[grepl("tom_level",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_level
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_player_role <- dd %>% 
  gather(trial, player_role, colnames(dd)[grepl("player_role",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  player_role
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_role <- dd %>% 
  gather(trial, tom_role, colnames(dd)[grepl("tom_role",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_role
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_decision <- dd %>% 
  gather(trial, decision, colnames(dd)[grepl("player.decision",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  decision
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_decision <- dd %>% 
  gather(trial, tom_decision, colnames(dd)[grepl("tom_decision",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_decision
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_player_payoff <- dd %>% 
  gather(trial, player_payoff, colnames(dd)[grepl("player_payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  player_payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_payoff <- dd %>% 
  gather(trial, tom_payoff, colnames(dd)[grepl("tom_payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_tom_state <- dd %>% 
  gather(trial, tom_state, colnames(dd)[grepl("tom_state",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  tom_state
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("player\\.payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

ddd <- merge(
  d_id_in_group,
  d_tom_level
) 
ddd <- merge(
  ddd,
  d_player_role
) 
ddd <- merge(
  ddd,
  d_tom_role
) 
ddd <- merge(
  ddd,
  d_decision
)
ddd <- merge(
  ddd,
  d_tom_decision
)
ddd <- merge(
  ddd,
  d_player_payoff
)
ddd <- merge(
  ddd,
  d_tom_payoff
)
ddd <- merge(
  ddd,
  d_tom_state
)
ddd <- merge(
  ddd,
  d_payoff
)
MatchingPennies3_Data <- subset(ddd, !is.na(id_in_group))
summary(MatchingPennies3_Data)

MatchingPennies2_Data$Framing <- "Human"
MatchingPennies3_Data$Framing <- "SlotMachine"

MatchingPennies_ToM_Data <- rbind(MatchingPennies2_Data, MatchingPennies3_Data)
write_csv(MatchingPennies3_Data, here("data", "clean", "MatchingPennies_TOM_data.csv"))


janitor::compare_df_cols(MatchingPennies_Data,MatchingPennies_ToM_Data)
```

# HAGEN
```{r}
dd <- data %>%
  select(
    colnames(data)[grepl("participant|Education|Year|Hagen_matrices",colnames(data))]
  )
dd_lc <- LastCall_data %>%
  select(
    colnames(LastCall_data)[grepl("participant|Education|Year|Hagen_matrices",colnames(LastCall_data))]
  )
dd_cs <- CogSci_2020_data %>%
  select(
    colnames(CogSci_2020_data)[grepl("participant|Education|Year|Hagen_matrices",colnames(CogSci_2020_data))]
  )

dd <- rbind(dd, dd_lc, dd_cs) %>%
  rename(
    participantPayoff = participant.payoff, 
    participantPayoff_Fee = participant.payoff_plus_participation_fee
  )

d_id_in_group <- dd %>% 
  gather(trial, id_in_group, colnames(dd)[grepl("id_in_group",colnames(dd))])  %>%
  select(
  participant.id_in_session,
  participant.code,
  Education,
  Year,
  trial,
  id_in_group
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_choice <- dd %>% 
  gather(trial, choice, colnames(dd)[grepl("choice",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  choice
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_correct_answer <- dd %>% 
  gather(trial, correct_answer, colnames(dd)[grepl("correct_answer",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  correct_answer
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )

d_right <- dd %>% 
  gather(trial, right, colnames(dd)[grepl("right",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  right
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
d_payoff <- dd %>% 
  gather(trial, payoff, colnames(dd)[grepl("payoff",colnames(dd))])  %>%
  select(
  participant.code,
  trial,
  payoff
  ) %>%
  mutate(
    trial = parse_number(gsub("\\.","",trial))
  )
ddd <- merge(d_id_in_group,
             d_choice)
ddd <- merge(ddd,
             d_correct_answer)
ddd <- merge(ddd,
             d_right)
ddd <- merge(ddd,
             d_payoff)
summary(ddd)
ddd <- ddd %>% subset(!is.na(id_in_group) & !is.na(choice))
write_csv(ddd, here("data", "clean", "Hagens_data.csv"))

```

## Imitation Inhibition

```{r}

# N.B. Three sites:
# - ImplicitImitationInhibition; Explicit_Imitation & Explicit_Inhibition (all 2019) Otree
# - CogSci_2018_ImitationInhibition PsychoPy
# - CogSci_2020_II (CogSci 2020) JsPsych

# Imitation Inhibition: (numbers are the cues)
# https://gitlab.pavlovia.org/maltelau/stroop
# Cognitive Science 28/08
# Engelsk 06/09
# Nordisk 25/09 and 26/09
# Lingvistik 12/09
# https://gitlab.pavlovia.org/Rnault/imitation-inhibition
# Religion Science 28/10
# Mediavidenskab 04/11
# Recall 06/11 and 07/11
# Digital Design 08/11
# Informationvidenskab 14/11
# ________________________________________________________
# Explicit Imitation: (no numbers, imitate the finger)
# https://gitlab.pavlovia.org/Rnault/stroop
# Cognitive Science 28/08
# Engelsk 06/09
# Nordisk 25/09 and 26/09
# Lingvistik 12/09
# https://gitlab.pavlovia.org/Rnault/explicit-imitation
# Religion Science 28/10
# Mediavidenskab 04/11
# Recall 06/11 and 07/11
# Digital Design 08/11
# Informationvidenskab 14/11
# ________________________________________________________
# Explicit Inhibition: (no numbers, lift the opposite finger)
# https://gitlab.pavlovia.org/Rnault/explicit-inhibition
# Religion Science 28/10
# Mediavidenskab 04/11
# Recall 06/11 and 07/11
# Digital Design 08/11
# Informationvidenskab 14/11

## FIRST implicit 2019
ImplicitImiInhi19_Data <- list.files(path="data/raw/ImplicitImitationInhibition/", pattern="csv",full.names = T) %>%
    purrr::map_df(read_csv)
## Identify incomplete trials
ImplicitImiInhi_Data <- subset(ImplicitImiInhi_Data, !is.na(condition))
x <- ImplicitImiInhi_Data %>% group_by(participant,condition) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())
## Anything below 60 looks dodgy
## ImplicitImiInhi_Data <- ImplicitImiInhi_Data %>% 
##  subset(!(participant %in% unique(x$participant[x$Trials<60])))

# SCIC: cue is a 1 and index moves
# SIII: cue is a 1 and middle moves
# SIIC: cue says 1, the index moves, but it's facing the participant's middle finger
# SCII: cue says 1, the middle finger moves, but it's facing the participant's index.

ImplicitImiInhi_Data$Congruency = "Incongruent"
ImplicitImiInhi_Data$Congruency[grepl("SCIC|SIIC",ImplicitImiInhi_Data$condition)] = "Congruent"
ImplicitImiInhi_Data$Orientation = "Compatible"
ImplicitImiInhi_Data$Orientation[grepl("SCII|SIIC",ImplicitImiInhi_Data$condition)] = "Mirrored"

## Then CogSci 2018
ImplicitImiInhi18_Data <-
  grep(list.files(path="data/raw/CogSci18/CogSci_2018_ImitationInhibition", full.names = T), pattern='exec|EI', invert=TRUE, value=TRUE) %>%
    purrr::map_df(read_csv)
summary(ImplicitImiInhi18_Data)
x <- ImplicitImiInhi18_Data %>% subset(is.na(Number_Cue))

## Then CogSci 2020
read1 <- function(filename){
  return(read_csv(filename, col_types = cols(
    rt = col_double(),
    key_press = col_double())))
}

ImplicitImiInhi20_Data <- list.files(path="data/raw/CogSci_2020_II/", pattern="csv",full.names = T) %>%
    purrr::map_df(read1)
summary(ImplicitImiInhi20_Data)
ImplicitImiInhi20_Data <- ImplicitImiInhi20_Data %>% subset(
  !is.na(rt) & !is.na(key_correct) & rt > 0
) %>% mutate(
  success = NULL,
  value = NULL,
  view_history = NULL
)
###

ExplicitImi_Data <- list.files(path="data/raw/Explicit_Imitation/", pattern="csv",full.names = T) %>%
    purrr::map_df(read_csv)

ExplicitInhi <- list.files(path="data/raw/Explicit_Inhibition/", pattern="csv",full.names = T) %>%
    purrr::map_df(read_csv)

## Identify incomplete trials
Mirror_Data1 <- subset(Mirror_Data1, !is.na(condition))
x <- Mirror_Data1 %>% group_by(participant,condition) %>% dplyr::summarize(Trials = n())
x1 <- x  %>% group_by(Trials) %>% summarize(Frequency=n())
## Anything below 60 looks dodgy
Mirror_Data1 <- subset(Mirror_Data1, !(participant %in% unique(x$participant[x$Trials<60])))


# IDENtIFY MISSING AND INCOMPLETE PARTICIPANTS
data$participant.code[!(data$participant.code %in% ImiInhi_Data$participant)]
data1 <- data[!(data$participant.code %in% ImiInhi_Data$participant),]
data1$ImitationInhibition <- "missing"
data1[,c("survey.1.player.pid","Class")]

# FULLY MISSING Explicit imitation
data$participant.code[!(data$participant.code %in% Mirror_Data1$participant)]
data2 <- data[!(data$participant.code %in% Mirror_Data1$participant),]
data2$ExplicitImitation <- "missing"
data2[,c("survey.1.player.pid","Class")]

d <- merge(data1, data2, all=T) %>%
  select(
    survey.1.player.pid,
    Class,
    ImitationInhibition,
    ExplicitImitation
  )

write_csv(d,"MissingTasks.csv")



ggplot(subset(Mirror_Data, participant=="23mbj83y"), aes(condition,resp.rt, color=finger)) + geom_jitter(width=0.1) + theme_classic()
ggplot(subset(ImiInhi_Data, participant=="23mbj83y"), aes(condition,resp.rt, color=finger)) + geom_jitter(width=0.1) + theme_classic()
ggplot(subset(ImiInhi_Data, resp.rt<2), aes(condition,resp.rt, color=finger)) + geom_jitter(width=0.1) + theme_classic()

length(unique(ImiInhi_Data$participant))
length(unique(Mirror_Data$participant))

x<-ImiInhi_Data %>% group_by(participant,condition) %>% dplyr::summarise(n())

m <- lmer(resp.rt ~ 0 + Congruency : Orientation + (0 + Congruency : Orientation|participant),ImiInhi_Data,REML=F)


m <- lmer(resp.rt ~ 1 + condition + (1 + condition|participant),Mirror_Data,REML=F)
summary(m)

```

# Create task matrix identifying who has which tasks
  
```{r}

gg <- data %>%
  select(participant.code,
         participant._current_app_name) %>%
  subset(participant._current_app_name!="total")

d0 <- gg %>% subset(
  participant._current_app_name=="prisoner_retaliation"
)

d0$PrisonerRetaliation <- "missing"

d1 <- gg %>% subset(
  participant._current_app_name=="prisoner_retaliation"| 
    participant._current_app_name=="CRD_sequential"
)

d1$CRD_sequential <- "missing"

d2 <- gg %>% subset(
  participant._current_app_name=="prisoner_retaliation" | 
    participant._current_app_name=="CRD_sequential"| 
    participant._current_app_name=="matching_pennies_bot"
)
d2$MatchingPennies <- "missing"

d3 <- gg %>% subset(
  participant._current_app_name=="prisoner_retaliation" |
  participant._current_app_name=="CRD_sequential" | 
  participant._current_app_name=="matching_pennies_bot" | 
  participant._current_app_name=="Hagen_matrices"
)
d3$HagenMatrices <- "missing"

MissingData <- merge(d0,d1, all=T)
MissingData <- merge(MissingData,d2, all=T)
MissingData <- merge(MissingData,d3, all=T)

data6 <- data[(data$participant.code %in% MissingData$participant.code),] %>%
  select(survey.1.player.pid,
         Class,
         participant.code
         )

data7 <- data %>% subset(Class!="Religion") %>%
  select(survey.1.player.pid,
         Class)
data7$ExplicitInhibition = "missing"


MissingData <- merge(data6, MissingData, all=T) 
MissingData <- merge(d, MissingData, all=T) 
MissingData <- MissingData %>% select(-participant.code, -participant._current_app_name)
MissingData <- merge( MissingData,data7, all=T) 

write_csv(MissingData,"MissingTasks.csv")
```

